<?php
if ($bannerInfo == null) {
    $pageTitle = "Thêm mới banner";
    $bannerInfo["title"] = "";
    $bannerInfo["link"] = "";
    $bannerInfo["img_path"] = "";
    $bannerInfo['status'] = 1;
} else {
    $pageTitle = "Sửa banner";
}
?>
<form id="edit_form" action="/admin/banner/post/id/<?php echo $id ?>" method="post" enctype="multipart/form-data">
    <div class="lblHeader"><h2><?php echo $pageTitle ?></h2></div>
    <div class="clr"></div>
    <div class="fl cateL">
        <div class="lblCategory fl">Tên banner: </div><div class="fl lineSpace"><input type="text" class="input-text" title="title" value="<?php echo $bannerInfo['title'] ?>" name="title" id="title"></div>
        <div class="lblCategory fl">Liên kết: </div><div class="fl lineSpace"><input type="text" class="input-text" title="link" value="<?php echo $bannerInfo['link'] ?>" name="link" id="link"></div>
        <div class="lblCategory fl">Ảnh: </div>
        <div class="fl lineSpace">       
            <div class="image_des fl">
                <img src="<?php
                if ($bannerInfo['img_path'] != "") {
                    echo AVATAR_PATH . $bannerInfo['img_path'];
                } else {
                    echo "/skin/default/images/no-image.png";
                }
                ?>" height="30px" />
            </div>
            <div class="upload_file fl">            
                <input type="file" name="file" id="file">
                <input type="hidden" name="img_path" id="img_path" value="<?php echo $bannerInfo['img_path'] ?>" />
            </div>                
        </div>
        <div class="clr"></div>        
        <?php /*
          <div class="lblCategory fl">Nhóm: </div><div class="fl lineSpace">
          <select name="type" id="type" class="sltCategoryType">
          <option value="0">Hãy chọn loại</option>
          <?php foreach($categoryTypes as $typeInfo){?>
          <option value="<?php echo $typeInfo["type_key"]?>" <?php if($categoryInfo['type'] == $typeInfo['type_key']) echo "selected=selected"?>><?php echo $typeInfo["type_name"]?>
          </option>
          <?php }?>
          </select>
          </div>
         * */
        ?>
        <div class="lblCategory fl">Trạng thái</div>
        <div class="fl lineSpace">
            <select name="status" id="status">
                <option <?php if ($bannerInfo['status'] == '0') { ?>selected="selected"<?php } ?> value="0">Khóa</option>
                <option <?php if ($bannerInfo['status'] == '1') { ?>selected="selected"<?php } ?> value="1">Hoạt động</option>
            </select>                        
        </div>           
        <div class="clr"></div> 
        <div class="lblCategory fl"></div><div class="fl lineSpace"><input type="submit" title="Lưu" id="cmd_submit" value="Lưu" /></div>            
    </div>
</form>
