<div class="BoxRight">
    <div class="BorderBottom">
        <div class="BoxRightCL"></div>
        <div class="BoxRightCC">
            <a id="ctl00_About1_rpt_head_ctl00_HplTitle"><?php echo $categoryInfo['title']; ?></a>
        </div>
        <div class="BoxRightCR"></div>
    </div>
    <div style="clear:both;"></div>
    <div class="NewsContent">
        <?php echo $article['detail']; ?>
    </div>
</div>
