<div>
    <section class="main_content">                                        
        <section class="content_detail">
            <section class="sec_content fl">
                <header>
                    <?php echo $categoryInfo['title']; ?>
                </header>
                <?php foreach ($articles as $article) { ?>                    
                    <article>
                        <?php if ($article['avatar_url'] != NULL) { ?>
                            <div class="cover" style="background-image: url(&quot;<?php echo AVATAR_RESIZE_PATH . "/180x110/" . $article['avatar_url'] ?>&quot;);"><a href="/<?php echo $article['url_key']; ?>/"></a></div>
                        <?php } else { ?>
                            <div class="cover" style="background-image: url(&quot;<?php echo AVATAR_RESIZE_PATH . "180x110/" . $article['avatar_url'] ?>&quot;);"><a href="/<?php echo $article['url_key']; ?>/"></a></div>
                        <?php } ?>
                        <header>
                            <p class="news_title"><a href="/<?php echo $article['url_key']; ?>"><?php echo $article['title']; ?></a></p>
                                <?php echo $article['description']; ?>
                        </header>                    
                    </article>                    
                <?php } ?>
            </section>                          
        </section>
    </section>    
</div>