<div class="div_header"></div>
<div class="clr"></div>
<div class="top_header">
    <div class="top_content">
        <!-- Main menu -->
        <div class="fl"><a href="/"><img src="<?php echo SKIN_PATH ?>/default/plugins/dropmenu/images/home_ico.png" /></a></div>
        <div class="nav fl">            
            <ul>                
                <li><a href="/web-sang-tao-net/">Websangtao.net</a></li>
                <li><a href="/lap-trinh/">Lập Trình</a>
                        <ul>
                                <li><a href="/html-css/">HTML &amp; CSS</a></li>
                                <li><a href="/asp-net-sql-server/">ASP.Net &amp; SQL Server</a></li>
                                <li><a href="/php-mysql/">PHP &amp; MySQL</a></li>
                        </ul>
                </li>
                <li><a href="/magento/">Magento</a></li>
                <li><a href="/asterisk/">Asterisk</a></li>
                <li><a href="/sf-cms/">SF cms</a></li>
                <li><a href="/lien-he/">Liên Hệ</a></li>
            </ul>            
        </div>
        <div class="hotline">            
            Hotline: 0973 001100            
        </div>
        <div class="clr"></div>
        <!-- End Main menu -->
    </div>
</div>