<title><?php echo $this->getTitle();?></title>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type">
<meta content="<?php echo $this->getDescription();?>" name="description">
<meta content="<?php echo $this->getKeywords();?>" name="keywords">
<meta content="INDEX,FOLLOW" name="robots">

<link href="<?php echo SKIN_PATH; ?>/default/css/styles.css" rel="stylesheet" type="text/css" />
<link href="<?php echo SKIN_PATH; ?>/default/plugins/dropmenu/css/menu.css" rel="stylesheet" type="text/css" />