<div class="BoxRight">
    <div class="BorderBottom">
        <div class="BoxRightCL"></div>
        <div class="BoxRightCC"><?php echo $categoryInfo['title']; ?></div>
        <div class="BoxRightCR"></div>
    </div>
    <div style="clear:both;"></div>
    <?php foreach ($products as $product) { ?>    
    <div class="ProItem">        
        <a href="/<?php echo $product['url_key']; ?>/">
            <?php if ($product['pro_image'] != NULL) { ?>
                <img width="91" src="<?php echo AVATAR_RESIZE_PATH . "/90x140/" . $product['pro_image'] ?>">
            <?php } else { ?>
                <img width="91" src="<?php echo SKIN_PATH ?>default/images/no-image.png">
            <?php } ?>
        </a>
        <a href="/<?php echo $product['url_key']; ?>/">
        <?php echo $product['pro_name']; ?>
        </a>            
    </div>
    <?php } ?>
</div>