<div class="BoxRight">
    <div class="proDetail">
        <div class="proLeft">
            <?php echo $product['pro_detail']; ?>
            <div class="proTech"></div>
        </div>
        <div class="proRight">
            <img style="width:200px;border-width:0px;" src="<?php echo AVATAR_RESIZE_PATH . "/180x280/" . $product['pro_image'] ?>" id="ctl00_ProductDetail1_proMainImage">
        </div>
        <div style="clear:both;"></div>
        
    </div>
</div>