<!-- Top -->
<div class="Top">
    <div class="logo">
        <img src="<?php echo SKIN_PATH ?>default/images/Logo.jpg"></div>
    <div class="CompanyName">
        <div id="css-shadow">
            <h1 class="font"><p><?php echo DEFAULT_TITLE; ?></p>GÓP SỨC VÌ TƯƠNG LAI</h1>
            <h1 class="shadow"><p><?php echo DEFAULT_TITLE; ?></p>GÓP SỨC VÌ TƯƠNG LAI</h1>
        </div>
    </div>
</div>
<!--End Top-->
<?php $this->block("menu") ?>
        