<tr><td height=5></td></tr>
<!--menu ngang-->
<tr>
    <td height=36>
        <table border=0 cellpadding=0 cellspacing=0 height=36 width=100%>
            <tr>
                <td background="<?php echo SKIN_PATH ?>default/images/bg-menu-left.gif" width=6></td>
                <td background="<?php echo SKIN_PATH ?>default/images/bg-menu.gif" width=639>
                    <table border="0" cellpadding=0 cellspacing=0 width="100%" height=100%>
                        <tr class="menu">
                            <td>
                                <a href="/">Trang chủ</a></td>
                            <td width=1><img src="<?php echo SKIN_PATH . "default/images/bg-menu-line.gif"?>"></td>                            
                            <?php echo $menuHtml;?>
                        </tr>
                    </table>
                </td>
                <td background="<?php echo SKIN_PATH ?>default/images/bg-menu-right.gif" width=6></td>
            </tr>
        </table>
    </td>
</tr>
<!--End menu ngang-->
<?php //echo $hotline;?>             
