<div class="images_library fl">
    <div class="right_block">
        <div class="title_box">
            <div class="left_box_title fl"></div>
            <div class="title_box_text">
                Thư viện ảnh
            </div>                            
        </div>
        <div class="right_box_list">
            <div class="img_item fl">
                <img src="images/noimage.jpg" />
            </div>
            <div class="img_item fl">
                <img src="images/noimage.jpg" />
            </div>
            <div class="img_item fl">
                <img src="images/noimage.jpg" />
            </div>
            <div class="img_item fl">
                <img src="images/noimage.jpg" />
            </div>
            <div class="img_item fl">
                <img src="images/noimage.jpg" />
            </div>
            <div class="img_item fl">
                <img src="images/noimage.jpg" />
            </div>                                
        </div>                        
    </div><!-- left_block -->                   
</div><!-- image lib -->