<section class="topic">
<header>
<h1><a title="Bài mới" href="#">Bài mới</a></h1>
</header>
<?php 
    $i = 0;
    foreach($lastestNews as $item){
        $i++;
?>
    
    <article <?php if($i == 1){ echo "class=\"featured\"";}?>>
        <?php if($item['avatar_url'] != NULL){?>
        <div class="cover" style="background-image: url(&quot;<?php echo AVATAR_RESIZE_PATH."280x200/".$item['avatar_url'] ?>&quot;);"><a href="/<?php echo $item['url_key'];?>/"></a></div>
        <?php } ?>
        <header>
        <h1>
        <a href="/<?php echo $item['url_key'];?>/">
        <?php echo $item['title'];?>
        </a>
        </h1>
        </header>
    </article>
<?php
    }        
?>
<!--<p class="btnMore"><a title="TOPIC_TITLE" href="/tieu-diem/tg-chuyen-4-phuong.html">Xem thêm</a></p>-->
</section>