<div class="left_panel fl">
    <div class="left_block">
        <div class="title_box">
            <div class="left_box_title fl"></div>
            <div class="title_box_text">
                Liên kết website
            </div>                            
        </div>
        <div class="left_box_list">
            <ul>
                <li>
                    <a href="#">Lợn Mường Khương</a>
                </li>                                
                <li>
                    <a href="#">Lợn Mường Khương</a>
                </li>        
                <li>
                    <a href="#">Lợn Mường Khương Lợn Mường Khương</a>
                </li>                                 
            </ul>
        </div>                        
    </div><!-- left_block -->    
    <?php $this->block("vnexpress") ?>
</div><!-- left_panel -->