<!--MenuH-->
<?php echo $scriptActive; ?>
<div id="ddtabs4" class="ddcolortabs">
    <ul>        
        <li style="width:25px; float:left;">&nbsp;</li>
        <li><a href="/" rel="ct1"><span>Trang chủ</span></a></li>
        <?php echo $menuHtml;?>
    </ul>
</div>
<div class="tabcontainer">
    <div id="ct1" class="tabcontent"> 
        <?php echo DEFAULT_TITLE; ?>
    </div>
    <?php echo $subMenu; ?>    
</div>        
<!--End MenuH-->