<!-- START SLIDER -->
<script type="text/javascript" src="<?php echo SKIN_PATH?>default/plugins/revolslider/js/jquery-migrate.js"></script>
<script type="text/javascript" src="<?php echo SKIN_PATH?>default/plugins/revolslider/js/jquery.js"></script>
<script type="text/javascript" src="<?php echo SKIN_PATH?>default/plugins/revolslider/js/jquery_009.js"></script>

<link rel="stylesheet" id="rev-google-font" href="<?php echo SKIN_PATH?>default/plugins/revolslider/css/revolslider.css" type="text/css" media="all">
<link rel="stylesheet" id="rs-settings-css" href="<?php echo SKIN_PATH?>default/plugins/revolslider/css/settings.css" type="text/css" media="all">
<link rel="stylesheet" id="rs-settings-css" href="<?php echo SKIN_PATH?>default/plugins/revolslider/css/captions.css" type="text/css" media="all">

<div id="rev_slider_1_1" class="rev_slider fullwidthabanner tp-simpleresponsive hovered">
    <ul style="display: block;">
        <?php foreach ($banners as $banner){?>
        <li style="visibility: visible; left: 0px; top: 0px; z-index: 20; opacity: 1;" data-transition="3dcurtain-vertical" data-slotamount="7">        
            <img src="<?php echo AVATAR_PATH?><?php echo $banner['img_path'] ?>"
        </li>
        <?php } ?>
    </ul>     
</div>
<script type="text/javascript" src="<?php echo SKIN_PATH?>default/plugins/revolslider/js/revolslider.js"></script>
<!-- END SLIDER -->