<script type="text/javascript" src="<?php echo SKIN_PATH?>default/plugins/unslider/js/unslider.js"></script>    
<link href="<?php echo SKIN_PATH; ?>default/plugins/unslider/css/unslider.css" rel="stylesheet" type="text/css" />

<div class="banner">
    <ul>
        <?php foreach ($banners as $banner){?>
        <li style="background-image: url(<?php echo AVATAR_PATH?><?php echo $banner['img_path'] ?>);"></li>
        <?php } ?>
    </ul>
</div>
<script type="text/javascript">        
$('.banner').unslider({
	speed: 1000,               //  The speed to animate each slide (in milliseconds)
	delay: 3000,              //  The delay between slide animations (in milliseconds)
	complete: function() {},  //  A function that gets called after every slide animation
	keys: true,               //  Enable keyboard (left, right) arrow shortcuts
	dots: false,               //  Display dot navigation
	fluid: false              //  Support responsive design. May break non-responsive designs
});
</script>