<section class="main_content">
    <section class="content_detail">
        <section class="sec_content fl">
            <header>
                Liên hệ
            </header>   
            <div class="news_item">
                <form id="edit_form" action="/default/feedback/post" method="post">                
                    <section class="fl cateL">
                        <section class="lblFeedback fl">Họ tên: </section>
                        <section class="fl">
                            <input type="text" class="input-text" title="Họ tên" value="" name="fullname" id="fullname">
                        </section>   
                        <section class="clr"></section>
                        <section class="lblFeedback fl">Email: </section>
                        <section class="fl">
                            <input type="text" class="input-text" title="Email" value="" name="email" id="email">
                        </section>    
                        <section class="clr"></section>
                        <section class="lblFeedback fl">Điện thoại: </section>
                        <section class="fl">
                            <input type="text" class="input-text" title="Điện thoại" value="" name="phone" id="phone">
                        </section>       
                        <section class="clr"></section>
                        <section class="lblFeedback fl">Nội dung: </section>
                        <section class="fl">
                            <textarea class="input-text" title="Nội dung" value="" name="content" id="content"></textarea>
                        </section>                    
                        <section class="clr"></section>
                        <section class="lblFeedback fl">&nbsp;</section><section class="fl lineSpace"><input type="submit" title="Gửi" id="cmd_submit" value="Gửi" /></section>                         <br />
                    </section>
                </form>
            </div>
        </section>                  
    </section>
</section>
