<section class="main_content">
    <section class="content_detail">
        <section class="column_left fl">
            <header>
                Liên hệ
            </header>                 
            <section class="fl cateL">
                Cảm ơn bạn đã gửi thông tin liên hệ. Chúng tôi sẽ phản hồi lại tron thời gian sớm nhất.
            </section>            
        </section>                 
    </section>
</section>