<link rel="stylesheet" type="text/css" href="/skin/admin/plugins/calendar/css/tcal.css" />
<script type="text/javascript" src="/skin/admin/plugins/calendar/js/tcal.js"></script> 
<?php
$date = "";
$hour = "";
$minute = "";
if ($articleInfo == null) {
    $pageTitle = 'Viết bài';
    $articleInfo['priority'] = '';
    $articleInfo['detail'] = '';
    $articleInfo['category_id'] = 0;
    $articleInfo['avatar_url'] = '';
    $articleInfo['status'] = 1;
} else {
    $pageTitle = 'Sửa bài viết';
    $arrDateTime = explode(" ", $articleInfo['public_time']);
//    var_dump($arrDateTime);exit;
    $currentDate = date_create(@$arrDateTime[0]);
    $date = date_format($currentDate, 'd/m/Y');
    $arrTime = explode(":", @$arrDateTime[1]);
    $hour = @$arrTime[0];
    $minute = @$arrTime[1];
}
?>
<form id="edit_form" action="/admin/article/post/id/<?php echo $id ?>" method="post" enctype="multipart/form-data">
    <div class="lblHeader"><h2><?php echo $pageTitle ?></h2></div>
    <div class="clr"></div>
    <section class="fl secEditor">        
        <div class="fl txtEditor">
            <?php
            $oFCKeditor = new FCKeditor('detail');
            $oFCKeditor->BasePath = '/lib/fckeditor/';
            $oFCKeditor->Value = $articleInfo['detail'];
            $oFCKeditor->Height = '500px';
            $oFCKeditor->Create();
            ?>  
        </div>    
        <div class="lblCategory fl">Ảnh minh họa: </div>
        <div class="fl lineSpace">       
            <div class="image_des fl">
                <img src="<?php
                if ($articleInfo['avatar_url'] != "") {
                    echo AVATAR_PATH . $articleInfo['avatar_url'];
                } else {
                    echo "/skin/default/images/no-image.png";
                }
                ?>" height="30px" />
            </div>
            <div class="upload_file fl">            
                <input type="file" name="file" id="file">
                <input type="hidden" name="avatar_url" id="avatar_url" value="<?php echo $articleInfo['avatar_url'] ?>" />
            </div>                
        </div>
    </section>
    <section class="sidebar fl">
        <div class="lblOrder fl">Thứ tự: </div>
        <div class="fl lineSpace"><input type="text" class="txtShort" value="<?php echo $articleInfo['priority'] ?>" name="priority" id="priority"></div>    
        <div class="clr"></div>     
        <div class="lblOrder fl">Lưu: </div>
        <div class="fl lineSpace">
            <select name="category_id" id="parent_id" multiple="multiple" class="sltCategory">
                <option value="0" <?php if ($articleInfo['category_id'] == 0) echo "selected=selected" ?>>Root</option>
                    <?php foreach ($categorys as $category) { ?>            
                    <option value="<?php echo $category["id"] ?>" <?php if ($articleInfo['category_id'] == $category['id']) echo "selected=selected" ?>><?php
                for ($k = 0; $k < $category["level"]; $k++) {
                    echo "....";
                } echo $category["title"]
                ?>                
                    </option>
<?php } ?>            
            </select>
        </div>
        <div class="clr"></div>
        <div class="lblOrder fl">Xuất bản: </div>
        <div class="fl lineSpace">
            <input type="text" name="public_time" id="public_time" class="tcal" value="<?php echo $date ?>" />
        </div>    
        <div class="lblOrder fl">Giờ: </div>
        <div class="fl lineSpace">
            <select name="sltH" id ="sltH">
                <?php
                for ($i = 0; $i < 24; $i++) {
                    if ($i < 10) {
                        ?>
                        <option <?php if ($hour == "0$i") { ?>selected="selected"<?php } ?> value="0<?php echo $i; ?>">0<?php echo $i ?></option>
    <?php } else { ?>
                        <option <?php if ($hour == "$i") { ?>selected="selected"<?php } ?> value="<?php echo $i; ?>"><?php echo $i ?></option>
                    <?php }
                }
                ?>
            </select>
            :
            <select name="sltM" id ="sltM">
                <?php
                for ($i = 0; $i < 60; $i++) {
                    if ($i < 10) {
                        ?>
                        <option <?php if ($minute == "0$i") { ?>selected="selected"<?php } ?> value="0<?php echo $i; ?>">0<?php echo $i ?></option>
    <?php } else { ?>
                        <option <?php if ($minute == "$i") { ?>selected="selected"<?php } ?> value="<?php echo $i; ?>"><?php echo $i ?></option>
    <?php }
}
?>
            </select>
        </div>       
        <div class="clr"></div>
        <div class="lblStatus fl">Trạng thái: </div>
        <div class="fl lineSpace">
            <select name="status" id="status">
                <option <?php if ($articleInfo['status'] == '0') { ?>selected="selected"<?php } ?> value="0">Khóa</option>
                <option <?php if ($articleInfo['status'] == '1') { ?>selected="selected"<?php } ?> value="1">Xuất bản</option>
            </select>
        </div>
        <div class="divCmdRight">
            <input type="hidden" id="title" name="title" value="0" />
            <input type="hidden" id="description" name="description" value="0" />
            <input type="submit" title="Save" id="cmd_submit" value="Lưu" />
        </div>
    </section>
</form>