<?php
if ($productInfo == null) {
    $pageTitle = 'Thêm ảnh';
    $productInfo['priority'] = '';
    $productInfo['pro_detail'] = '';
    $productInfo['pro_image'] = '';
    $productInfo['category_id'] = 0;
} else {
    $pageTitle = 'Sửa ảnh';
}
?>
<form id="edit_form" action="/admin/product/post/id/<?php echo $id ?>" method="post" enctype="multipart/form-data">
    <div class="lblHeader"><h2><?php echo $pageTitle ?></h2></div>
    <div class="clr"></div>
    <section class="fl secEditor"> 
        <div class="fl txtEditor">
            <?php
            $oFCKeditor = new FCKeditor('pro_detail');
            $oFCKeditor->BasePath = '/lib/fckeditor/';
            $oFCKeditor->Value = $productInfo['pro_detail'];
            $oFCKeditor->Height = '500px';
            $oFCKeditor->Create();
            ?>    
        </div>
        <div class="lblCategory fl">Ảnh minh họa: </div>
        <div class="fl lineSpace">       
            <div class="image_des fl">
                <img src="<?php
                if ($productInfo['pro_image'] != "") {
                    echo AVATAR_PATH . $productInfo['pro_image'];
                } else {
                    echo "/skin/default/images/no-image.png";
                }
                ?>" height="30px" />
            </div>
            <div class="upload_file fl">            
                <input type="file" name="file" id="file">
                <input type="hidden" name="pro_image" id="pro_image" value="<?php echo $productInfo['pro_image'] ?>" />
            </div>                
        </div>
    </section>
    <section class="sidebar fl">
        <div class="lblCategory fl">Thứ tự: </div><div class="fl lineSpace"><input type="text" class="txtShort" value="<?php echo $productInfo['priority'] ?>" name="priority" id="priority"></div>
        <div class="clr"></div>
        <div class="lblOrder fl">Lưu: </div>
        <div class="fl lineSpace">
            <select name="category_id" id="parent_id" multiple="multiple" class="sltCategory">
                <option value="0" <?php if ($productInfo['category_id'] == 0) echo "selected=selected" ?>>Root</option>
                    <?php foreach ($categorys as $category) { ?>            
                    <option value="<?php echo $category["id"] ?>" <?php if ($productInfo['category_id'] == $category['id']) echo "selected=selected" ?>><?php
                for ($k = 0; $k < $category["level"]; $k++) {
                    echo "....";
                } echo $category["title"]
                ?>                
                    </option>
<?php } ?>            
            </select>
        </div>
        <div class="clr"></div>
        <div class="divCmdRight">
            <input type="hidden" id="title" name="pro_name" value="0" />
            <input type="hidden" id="description" name="pro_des" value="0" />
            <input type="submit" title="Save" id="cmd_submit" value="Save" />
        </div>
    </section>
</form>