<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>SF-CMS</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link href="<?php echo SKIN_PATH; ?>admin/css/styles.css" rel="stylesheet" type="text/css" />
        <script src="<?php echo SKIN_PATH; ?>admin/js/sf_admin.js" type="text/javascript"></script>      
        <link href="<?php echo SKIN_PATH; ?>/admin/plugins/dropmenu/css/menu.css" rel="stylesheet" type="text/css" />  
        <link rel="shortcut icon" href="<?php echo SKIN_PATH; ?>default/images/favicon.ico" />
    </head>
    <body>        
        <div class="wrapper">                
            <?php $this->block("header") ?>
            <div class="container">
                <div class="main_content">
                    <div class="content fl">
                        <?php $this->content() ?>
                    </div>  
                    <div class="clr"></div>
                </div>
            </div>
            <div class="clr"></div>
            <?php $this->block("footer") ?>        
        </div>     
        <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-23119574-2']);
        _gaq.push(['_trackPageview']);

        (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

        </script>        
    </body>
</html>