<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title><?php echo $this->getTitle(); ?></title>
        <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
        <meta content="<?php echo $this->getDescription(); ?>" name="description" />
        <meta content="<?php echo $this->getKeywords(); ?>" name="keywords" />
        <meta content="INDEX,FOLLOW" name="robots" />

        <script type="text/javascript" src="<?php echo SKIN_PATH ?>default/js/jquery-1.10.2.js"></script>            

        <link href="<?php echo SKIN_PATH; ?>default/css/styles.css" rel="stylesheet" type="text/css" />        
        <link rel="shortcut icon" href="<?php echo SKIN_PATH; ?>default/images/favicon.ico" />
    </head>
    <body>        
        <div class="wrapper">
            <div class="container">                         
                <?php $this->block("header") ?>
                <div class="main_body">
                    <?php $this->block("left") ?>
                    <div class="right_panel fl">
                        <div class="main_content fl">                        
                            <?php $this->content() ?>
                        </div>
                        <div class="clr"></div>
                        <?php $this->block("image_lib") ?>
                        <?php $this->block("lastest_news") ?>
                    </div><!-- right_panel -->     
                    <div class="clr"></div>
                </div><!-- main_body -->            
                <?php $this->block("footer") ?>
            </div>
        </div>                                                                                    
    </body>
</html>