<?php
if ($userInfo == null) {
    $pageTitle = "Thêm mới người dùng";
    $userInfo["username"] = "";
    $userInfo["display_name"] = "";
    $userInfo["email"] = "";
    $userInfo["password"] = "";
    $userInfo['status'] = 1;
} else {
    $pageTitle = "Sửa người dùng";
}
?>
<form id="edit_form" action="/admin/user/post/id/<?php echo $id ?>" method="post">
    <div class="lblHeader"><h2><?php echo $pageTitle ?></h2></div>
    <div class="clr"></div>
    <div class="fl cateL">
        <div class="lblCategory fl">Tên truy cập: </div><div class="fl lineSpace"><input type="text" class="input-text" title="User Name" value="<?php echo $userInfo['username'] ?>" name="username" id="username"></div>
        <div class="lblCategory fl">Mật khẩu: </div><div class="fl lineSpace"><input type="password" class="input-text" title="Password" value="<?php echo $userInfo['password'] ?>" name="password" id="password"></div>
        <div class="lblCategory fl">Tên hiển thị: </div><div class="fl lineSpace"><input type="text" class="input-text" title="Display Name" value="<?php echo $userInfo['display_name'] ?>" name="display_name" id="display_name"></div>
        <div class="clr"></div>
        <div class="lblCategory fl">Email: </div><div class="fl lineSpace"><input type="text" class="input-text" value="<?php echo $userInfo['email'] ?>" name="email" id="email"></div>            
        <?php /*
          <div class="lblCategory fl">Nhóm: </div><div class="fl lineSpace">
          <select name="type" id="type" class="sltCategoryType">
          <option value="0">Hãy chọn loại</option>
          <?php foreach($categoryTypes as $typeInfo){?>
          <option value="<?php echo $typeInfo["type_key"]?>" <?php if($categoryInfo['type'] == $typeInfo['type_key']) echo "selected=selected"?>><?php echo $typeInfo["type_name"]?>
          </option>
          <?php }?>
          </select>
          </div>
         * */
        ?>
        <div class="lblCategory fl">Trạng thái</div>
        <div class="fl lineSpace">
            <select name="status" id="status">
                <option <?php if ($userInfo['status'] == '0') { ?>selected="selected"<?php } ?> value="0">Khóa</option>
                <option <?php if ($userInfo['status'] == '1') { ?>selected="selected"<?php } ?> value="1">Hoạt động</option>
            </select>                        
        </div>           
        <div class="clr"></div> 
        <div class="lblCategory fl"></div><div class="fl lineSpace"><input type="submit" title="Lưu" id="cmd_submit" value="Lưu" /></div>            
    </div>
</form>
