<table border=0 cellpadding=0 cellspacing=0 width=100%>
    <tr><td height=50 class="title-menu"><img src="<?php echo SKIN_PATH ?>default/images/icon.gif" style="margin:5px 5px 0px 0px;">GIỚI THIỆU<br><hr color=#dfdfdf></td></tr>
    <tr><td>
            <div class="news_item">
                <?php foreach ($articles as $article) { ?>
                    <?php echo $article['detail']; ?>
                <?php } ?>
            </div>            
        </td></tr>
</table>