<!--Introduction-->
<div class="BoxRight">
    <div class="BorderBottom">
        <div class="BoxRightCL"></div>
        <div class="BoxRightCC">Giới thiệu về công ty</div>
        <div class="BoxRightCR"></div>    									
        <div style="clear:both;"></div>
    </div>
    <div class="NewsItem">
        <?php foreach ($articles as $article) { ?>
            <?php echo $article['description']; ?>
        <?php } ?>         
    </div>
</div>
<!--End Introduction-->		
<!-- Thuong hieu -->
<div class="BoxRight">
    <div class="BorderBottom">
        <div class="BoxRightCL"></div>
        <div class="BoxRightCC">Các thương hiệu phát triển</div>
        <div class="BoxRightCR"></div>
    </div>		
    <div style="clear:both;"></div>			

    <div class="LogoItem">
        <a href="#">
            <img width="91" src="<?php echo SKIN_PATH ?>default/images/thuonghieu/thong_nhat.jpeg">
        </a>

    </div>

    <div class="LogoItem">
        <a href="#">
            <img width="91" src="<?php echo SKIN_PATH ?>default/images/thuonghieu/Cozy.jpeg">
        </a>

    </div>

    <div class="LogoItem">
        <a href="#">
            <img width="91" src="<?php echo SKIN_PATH ?>default/images/thuonghieu/Vinataba.jpeg">
        </a>

    </div>

    <div class="LogoItem">
        <a href="#">
            <img width="91" src="<?php echo SKIN_PATH ?>default/images/thuonghieu/trungnguyen.JPG">
        </a>

    </div>

    <div class="LogoItem">
        <a href="#">
            <img width="91" src="<?php echo SKIN_PATH ?>default/images/thuonghieu/Vinacafe.jpeg">
        </a>

    </div>

    <div class="LogoItem">
        <a href="#">
            <img width="91" src="<?php echo SKIN_PATH ?>default/images/thuonghieu/luong_thuc_tien_giang.jpeg">
        </a>

    </div>

    <div class="LogoItem">
        <a href="#">
            <img width="91" src="<?php echo SKIN_PATH ?>default/images/thuonghieu/xnk_thuy_san.jpeg">
        </a>

    </div>

    <div class="LogoItem">
        <a href="#">
            <img width="91" src="<?php echo SKIN_PATH ?>default/images/thuonghieu/Vinamilk.jpeg">
        </a>

    </div>

    <div class="LogoItem">
        <a href="#">
            <img width="91" src="<?php echo SKIN_PATH ?>default/images/thuonghieu/Sabeco.jpeg">
        </a>

    </div>

    <div class="LogoItem">
        <a href="#">
            <img width="91" src="<?php echo SKIN_PATH ?>default/images/thuonghieu/ki_thuat_dau_khi.jpeg">
        </a>

    </div>

    <div class="LogoItem">
        <a href="#">
            <img width="91" src="<?php echo SKIN_PATH ?>default/images/thuonghieu/Techcombank.jpeg">
        </a>

    </div>

    <div class="LogoItem">
        <a href="#">
            <img width="91" src="<?php echo SKIN_PATH ?>default/images/thuonghieu/BIDV.jpeg">
        </a>

    </div>

    <div class="LogoItem">
        <a href="#">
            <img width="91" src="<?php echo SKIN_PATH ?>default/images/thuonghieu/nh_cong_thuong.jpeg">
        </a>

    </div>

    <div class="LogoItem">
        <a href="#">
            <img width="91" src="<?php echo SKIN_PATH ?>default/images/thuonghieu/nh_ngoai_thuong.jpeg">
        </a>

    </div>

    <div class="LogoItem">
        <a href="#">
            <img width="91" src="<?php echo SKIN_PATH ?>default/images/thuonghieu/Bitis.jpeg">
        </a>

    </div>

    <div class="LogoItem">
        <a href="#">
            <img width="91" src="<?php echo SKIN_PATH ?>default/images/thuonghieu/an_phuoc.jpeg">
        </a>

    </div>

    <div class="LogoItem">
        <a href="#">
            <img width="91" src="<?php echo SKIN_PATH ?>default/images/thuonghieu/nha_be.jpeg">
        </a>

    </div>

    <div class="LogoItem">
        <a href="#">
            <img width="91" src="<?php echo SKIN_PATH ?>default/images/thuonghieu/phong_phu.jpeg">
        </a>

    </div>

    <div class="LogoItem">
        <a href="vit.net.vn">
            <img width="91" src="<?php echo SKIN_PATH ?>default/images/thuonghieu/Viettien.jpeg">
        </a>

    </div>

</div>
<!-- End thuong hieu -->
<!-- Product -->
